### PR TITLE
fix atEnd

### PR DESCRIPTION
**Pull request by ivanmem**

### CODE REVIEW

**Comment by WinXaito** [comment]
Hi, thanks for your PR.

I'm not sure about that, because the getter `atEnd` will check on the scroll controller offset. And the scroll controller obvisously point at the beggining of the page.

See the test:

```dart
test('Is At End', (){
    controller.scrollToStart();
    expect(controller.atEnd, false);
    controller.scrollToEnd();
    expect(controller.atEnd, true);
});
```

I'm open to heard more about it if you think it's right.

**Comment by ivanmem** [comment]
Currently, `atEnd` can be `true` after the `scrollToEnd` function has been executed and never again.
`scrollToEnd` scrolls to `max` programmatically, so the test completes successfully. Try manually scrolling to the end and comparing "max" with "offset".

**Comment by WinXaito** [comment]
I tested with the example app. I just add this to see the value of `atStart` and `atEnd`:

```dart
Text('At start: ${controller.atStart}'),
Text('At end: ${controller.atEnd}'),
```

And I got this:

scroll_pos_atEnd

If I apply your modification, `atEnd` is always at false.


`max` is returning this: `position.maxScrollExtent`, so theoretically, checking `offset == max` should be right.

**Comment by ivanmem** [comment]
Oh, you're right. I had an error in the code. I apologize for wasting your time.

**Comment by WinXaito** [comment]
> Oh, you're right. I had an error in the code. I apologize for wasting your time.

No worries it's fine ;)

**Pull request closed without merging**
